import dotenv from 'dotenv';
dotenv.config();

export const TMDB_CONFIG = {
  BASE_URL: 'https://api.themoviedb.org/3',
  IMAGE_BASE_URL: 'https://image.tmdb.org/t/p',
  POSTER_SIZES: {
    thumb: 'w185',
    medium: 'w342',
    large: 'w500',
    original: 'original',
  },
  BACKDROP_SIZES: {
    medium: 'w780',
    large: 'w1280',
    original: 'original',
  },
  API_KEY: process.env.TMDB_API_KEY || '8265bd1679663a7ea12ac168da84d2e8', // Default public demo key
  ACCESS_TOKEN: process.env.TMDB_ACCESS_TOKEN || '',
  TIMEOUT_MS: 3500, // Fast 3.5s timeout for snappy UX
  CACHE_TTL_HOURS: 24, // DB Cache TTL for movies
};

export const GENRE_MAP = {
  28: 'Action',
  12: 'Adventure',
  16: 'Animation',
  35: 'Comedy',
  80: 'Crime',
  99: 'Documentary',
  18: 'Drama',
  10751: 'Family',
  14: 'Fantasy',
  36: 'History',
  27: 'Horror',
  10402: 'Music',
  9648: 'Mystery',
  10749: 'Romance',
  878: 'Science Fiction',
  10770: 'TV Movie',
  53: 'Thriller',
  10752: 'War',
  37: 'Western',
};

// Fallback curated dataset for instant zero-config testing or when TMDB API is offline
export const FALLBACK_MOVIES = [
  {
    id: 550,
    title: 'Fight Club',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    posterPath: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    releaseDate: '1999-10-15',
    voteAverage: 8.44,
    voteCount: 29000,
    runtime: 139,
    genres: ['Drama', 'Thriller', 'Comedy'],
    cast: ['Edward Norton', 'Brad Pitt', 'Helena Bonham Carter', 'Meat Loaf'],
    directors: ['David Fincher'],
    trailerKey: 'O1nDozs-L58',
    popularity: 98.4,
  },
  {
    id: 27205,
    title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    posterPath: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    releaseDate: '2010-07-15',
    voteAverage: 8.37,
    voteCount: 36000,
    runtime: 148,
    genres: ['Action', 'Science Fiction', 'Adventure'],
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    directors: ['Christopher Nolan'],
    trailerKey: 'YoHD9XEInc0',
    popularity: 145.2,
  },
  {
    id: 157336,
    title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    posterPath: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    releaseDate: '2014-11-05',
    voteAverage: 8.45,
    voteCount: 34500,
    runtime: 169,
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
    directors: ['Christopher Nolan'],
    trailerKey: 'zSWdZVtXT7E',
    popularity: 160.8,
  },
  {
    id: 155,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    releaseDate: '2008-07-16',
    voteAverage: 8.51,
    voteCount: 32000,
    runtime: 152,
    genres: ['Drama', 'Action', 'Crime', 'Thriller'],
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
    directors: ['Christopher Nolan'],
    trailerKey: 'EXeTwQWrcwY',
    popularity: 130.5,
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
    posterPath: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s520QIq.jpg',
    releaseDate: '2024-02-27',
    voteAverage: 8.16,
    voteCount: 6100,
    runtime: 166,
    genres: ['Science Fiction', 'Adventure'],
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem'],
    directors: ['Denis Villeneuve'],
    trailerKey: 'Way9Dexny3w',
    popularity: 210.3,
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II.',
    posterPath: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    releaseDate: '2023-07-19',
    voteAverage: 8.09,
    voteCount: 9200,
    runtime: 180,
    genres: ['Drama', 'History'],
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    directors: ['Christopher Nolan'],
    trailerKey: 'uYPbbksJxIg',
    popularity: 180.2,
  },
  {
    id: 389,
    title: '12 Angry Men',
    overview: 'The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case of murder soon becomes a mini-drama of each of the jurors\' prejudices and preconceptions about the trial, the accused, and each other.',
    posterPath: 'https://image.tmdb.org/t/p/w500/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/qqHQsStV6Zg14L27d14B74kZeq8.jpg',
    releaseDate: '1957-04-10',
    voteAverage: 8.54,
    voteCount: 8800,
    runtime: 96,
    genres: ['Drama'],
    cast: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam', 'John Fiedler'],
    directors: ['Sidney Lumet'],
    trailerKey: 'TEN-2uTi2c0',
    popularity: 85.0,
  },
  {
    id: 238,
    title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    posterPath: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropPath: 'https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    releaseDate: '1972-03-14',
    voteAverage: 8.69,
    voteCount: 20000,
    runtime: 175,
    genres: ['Drama', 'Crime'],
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Robert Duvall'],
    directors: ['Francis Ford Coppola'],
    trailerKey: 'sY1S34973zA',
    popularity: 175.4,
  }
];
